apiVersion: v1
kind: Service
metadata:
  namespace: apache
  name: drill-service
spec:
  ports:
  - name: http
    port: 8047
  - name: userport
    port: 31010
  - name: controlport
    port: 31011
  - name: dataport
    port: 31012
  selector:
   app: drill-app
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: apache
  name: drillbit
spec:
  serviceName: drill-service
  replicas: 1
  template:
    metadata:
      labels:
        app: drill-app
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - drill-app
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: drill-pod
        imagePullPolicy: Always
        image: apache/drill:1.19.0
        ports:
        - containerPort: 8047
          name: http
        - containerPort: 31010
          name: userport
        - containerPort: 31011
          name: controlport
        - containerPort: 31012
          name: dataport
      initContainers:
      - name: zk-available
        image: busybox
        command: ['sh', '-c', 'until nc -z zk-service 2181; do echo Waiting for ZK to come up; sleep 5; done; ']
